# Module contains the 'used in ANZ project.
CB_ML_COMMON = 'cb_ml_common'
INSTALLATION_DIR = 'installation_dir'
ENSEMBLER = 'ensembler'
ML_OUT_DIR = 'ml_out_dir'
ENSEMBLER_OUTPUT = 'ensembler_output'
ENSEMBLER_SCRIPT = 'ensembler_script'
OUTPUT_DIR = 'output_dir'
PROCESSED_DIR = 'processed_dir'
INPUT_DIR = 'input_dir'
ML_CONFIG_FILE = 'config/ml_jobs_config.json'
LOG_CONFIG_FILE = 'config/logconfig.ini'

PREDICT = 'predict'
SERVE_URL = 'serve_url'
HEADERS = 'headers'
CLASSES = 'classes'
PREDICT_IMAGE_PATH = 'predict_image_path'
PREDICT_FILE_PATH = 'predict_file_path'

TRAIN = 'train'
EXPERIMENT_NAME = 'experiment_name'
IMAGE_WIDTH = 'image_width'
IMAGE_HEIGHT = 'image_height'
DATA_DIR = 'data_dir'
RAW_INPUT_DATA_DIR = 'raw_input_data_dir'
TRAIN_DATA_DIR = 'train_data_dir'
VALIDATION_DATA_DIR = 'validation_data_dir'
NB_TRAIN_SAMPLES = 'nb_train_samples'
NB_VALIDATION_SAMPLES = 'nb_validation_samples'
BATCH_SIZE = 'batch_size'
EPOCHS = 'epochs'

SCOPES = 'scopes'
